// <auto-generated />
namespace PolygonStocks.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<Model.PolygonContext>)>]
[<Migration("20210422180524_AddTickers")>]
type AddTickers() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.CreateTable(
            name = "Tickers"
            ,columns = (fun table -> 
            {|
                Ticker =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
                Name =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                Locale =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                Currency =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                PrimaryExchange =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
            |})
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_Tickers", (fun x -> (x.Ticker) :> obj)) |> ignore
                ) 
        ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "Tickers"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasAnnotation("ProductVersion", "5.0.5")
            |> ignore

        modelBuilder.Entity("Model+AggregatedBar", (fun b ->

            b.Property<string>("Ticker")
                .HasColumnType("TEXT") |> ignore
            b.Property<Int64>("TimestampSecs")
                .HasColumnType("INTEGER") |> ignore
            b.Property<decimal>("Close")
                .IsRequired()
                .HasColumnType("TEXT") |> ignore
            b.Property<decimal>("Highest")
                .IsRequired()
                .HasColumnType("TEXT") |> ignore
            b.Property<decimal>("Lowest")
                .IsRequired()
                .HasColumnType("TEXT") |> ignore
            b.Property<int>("NumberOfTransactions")
                .HasColumnType("INTEGER") |> ignore
            b.Property<decimal>("Open")
                .IsRequired()
                .HasColumnType("TEXT") |> ignore
            b.Property<decimal>("PriceWeightedByVolume")
                .HasColumnType("TEXT") |> ignore
            b.Property<int>("Volume")
                .IsRequired()
                .HasColumnType("INTEGER") |> ignore

            b.HasKey("Ticker", "TimestampSecs") |> ignore

            b.ToTable("AggregatedBars") |> ignore

        )) |> ignore

        modelBuilder.Entity("Model+InactiveTicker", (fun b ->

            b.Property<string>("Ticker")
                .HasColumnType("TEXT") |> ignore

            b.HasKey("Ticker") |> ignore

            b.ToTable("InactiveTickers") |> ignore

        )) |> ignore

        modelBuilder.Entity("Model+QueuedTicker", (fun b ->

            b.Property<string>("Ticker")
                .HasColumnType("TEXT") |> ignore

            b.HasKey("Ticker") |> ignore

            b.ToTable("QueuedTickers") |> ignore

        )) |> ignore

        modelBuilder.Entity("Model+Ticker", (fun b ->

            b.Property<string>("Ticker")
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Currency")
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Locale")
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Name")
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("PrimaryExchange")
                .HasColumnType("TEXT") |> ignore

            b.HasKey("Ticker") |> ignore

            b.ToTable("Tickers") |> ignore

        )) |> ignore

